# Generated by Django 5.0.2 on 2024-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_attestationresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_rating_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
