# Generated by Django 5.0.2 on 2024-02-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baseuser_rating_beltdescription_kicks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Учасника', 'verbose_name_plural': 'Учасники'},
        ),
    ]
