# Generated by Django 5.0.2 on 2024-02-21 21:05

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_baseuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='links',
            field=django_jsonform.models.fields.ArrayField(base_field=models.URLField(blank=True, null=True, verbose_name='Силка на соціальну мережу'), blank=True, null=True, size=8, verbose_name='Силки на соц. мережі'),
        ),
    ]
