# Generated by Django 5.0.2 on 2024-02-22 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0002_alter_group_options_alter_gym_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.group', verbose_name='Група')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gym', verbose_name='Спортзал')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
            },
        ),
        migrations.CreateModel(
            name='AttendanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('pre', 'Присутній'), ('ill', 'Захворів'), ('aps', 'Відсутній'), ('gre', 'Поважна причина')], max_length=3, verbose_name='Причина')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Коментар')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance', verbose_name='Відвідування')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Запис відвідування',
                'verbose_name_plural': 'Записи відвідувань',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='participants',
            field=models.ManyToManyField(related_name='attendance_participants', through='attendance.AttendanceUser', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен'),
        ),
    ]
