# Generated by Django 5.0.2 on 2024-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='attendance_type',
            field=models.CharField(choices=[('pre', 'Присутній'), ('ill', 'Захворів'), ('aps', 'Відсутній'), ('gre', 'Поважна причина')], default='pre', max_length=3, verbose_name='Причина'),
        ),
    ]
