# Generated by Django 4.2.10 on 2024-02-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_alter_attendanceuser_attendance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuser',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_to_attendance', to='attendance.attendance', verbose_name='Відвідування'),
        ),
        migrations.AlterField(
            model_name='attendanceuser',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_to_participant', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен'),
        ),
    ]
