# Generated by Django 5.0.2 on 2024-02-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Фото новини', 'verbose_name_plural': 'Фото новин'},
        ),
    ]
