# Generated by Django 5.0.2 on 2024-02-21 19:40

import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('calendar', models.CharField(max_length=250, verbose_name='Дні занять')),
                ('time', models.CharField(max_length=250, verbose_name='Час заняття')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Координати')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('calendar', models.CharField(max_length=250, verbose_name='Дні занять групи')),
                ('time', models.CharField(max_length=250, verbose_name='Час заняття групи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('participants', models.ManyToManyField(related_name='group_participants', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмени')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.gym', verbose_name='Спортзал')),
            ],
        ),
    ]
